### ISSUE TITLE
Problem Linking MLPACK on Mac

### ISSUE THREAD

**Issue by emmanuj** [mlpack/mlpack#441]
I'm trying to use the kmeans module. Below is the example source and the error I get:

		using namespace mlpack::kmeans;
		using namespace mlpack::metric;
		// The dataset we are clustering.
		arma::mat data(1, edges.size());
		int col =0;
		for(Edge& e: edges){
			//std::cout<<e<<std::endl;
			data(0,col) = e.weight;
			col++;
		}
		
		// The number of clusters we are getting.
		size_t clusters = 5;
		// The centroids will be stored in this matrix.
		
		
		// The assignments will be stored in this vector.
		arma::Col<size_t> assignments;

		// Initialize with the default arguments.
		//KMeans<SquaredEuclideanDistance,RefinedStart, MaxVarianceNewCluster> k;
		KMeans<> k;
		//RefinedStart k;
		k.Cluster(data, clusters, assignments);

		for(int i =0;i<edges.size();i++){
			std::cout<<edges[i].weight<<" "<<assignments(i)<<std::endl;
		}

And I get the following linker error:

    Undefined symbols for architecture x86_64:
    "mlpack::util::PrefixedOutStream::operator<<(std::basic_ostream<char, std::char_traits<char> >& (*)       (std::basic_ostream<char, std::char_traits<char> >&))", referenced from:
      Graph::sparsifyGraph()      in graph.o
    ld: symbol(s) not found for architecture x86_64
    collect2: error: ld returned 1 exit status
    make: *** [run] Error 1    

I get the same error whether I install mlpack with homebrew or from source. I'm using a Macbook pro with OSX 10.10 Yosemite.

Any help would be appreciated.

**Comment by rcurtin** [comment]
`Graph::sparsifyGraph()` isn't a symbol that I recognize as part of mlpack.  Can you show me how you are compiling (including how you are creating `graph.o`) and linking?

Thanks!

**Comment by emmanuj** [comment]
`Graph::sparsifyGraph()` is my function. 

    void Graph::sparsifyGraph(){
        for(Node& nod: nodes){
		std::vector<Edge> edges;
		double total =0;
		for(Neighbor& nb:neighbors(nod.getNodeId())){
			if(nod.getNodeId() > nb.nodeId) continue;
			Edge edge(nod, getNode(nb.nodeId), nb.algebraicDist);
			total+=nb.algebraicDist;
			edges.push_back(edge);
		}

		/*const double mean = total/edges.size();
		//sort the edges according to the algebraic distance
		sort(edges.begin(), edges.end(),SortByAlgebraicDistance());
		int p = edges.size() * 0.5;
		double median =0;
		if(p%2==0){
			median = (edges[p-1].weight + edges[p].weight) *0.5;
		}else{
			median = edges[p-1].weight;
		}
		std::cout<<mean<<" "<<median<<std::endl;*/

		//lets try k-means
		using namespace mlpack::kmeans;
		using namespace mlpack::metric;
		// The dataset we are clustering.
		arma::mat data(1, edges.size());
		int col =0;
		for(Edge& e: edges){
			//std::cout<<e<<std::endl;
			data(0,col) = e.weight;
			col++;
		}
		
		// The number of clusters we are getting.
		size_t clusters = 5;
		// The centroids will be stored in this matrix.
		// The assignments will be stored in this vector.
		arma::Col<size_t> assignments;

		// Initialize with the default arguments.
		//KMeans<SquaredEuclideanDistance,RefinedStart, MaxVarianceNewCluster> k;
		KMeans<> k;
		//RefinedStart k;
		k.Cluster(data, clusters, assignments);

		for(int i =0;i<edges.size();i++){
			std::cout<<edges[i].weight<<" "<<assignments(i)<<std::endl;
		}
		//std::cout<<edges.size()<<" "<<assignments.size()<<std::endl;
		//exit(0);
	}
    }

This is what my Makefile look like:


     # Warnings frequently signal eventual errors:
     CXXFLAGS=-std=c++11 -g -O3 #-W -Wall -Weffc++ -Wextra -pedantic -O3

     #Includes
     INCLUDES=-I/usr/include/libxml2/ -I/usr/local/include/mlpack -I/Users/emmanueljohn/libs/NetworKit/include
     LFLAGS=-L/Users/emmanueljohn/libs/NetworKit

    #Linker flags for both OS X and Linux
    LDFLAGS=-lexpat -fopenmp -lmlpack #-lNetworKit 

    # Generates list of object files from all the
    #   source files in directory
    OBJS = $(addsuffix .o, $(basename $(shell find *.cpp)))
    DEPS = $(OBJS:.o=.d)

    # Set executable name
    EXEC = run

    # Declare the phony targets
    .PHONY: echo clean r clang gcc setclang setgcc vg

    # Phony targets to run dependencies in order
    gcc: | setgcc $(EXEC)
    clang: | setclang $(EXEC)

    # For use with the clang static analyzer by
    #  using the environment variable for CXX
    sb: | $(clean) $(EXEC)

    vg: $(EXEC)
	    valgrind ./$(EXEC)

    # Run the executable
    r:
	./$(EXEC)

    clean:
	rm -rf $(OBJS)
	rm -rf $(DEPS)
	rm -rf $(EXEC)

    # Phony target to use clang for compile and linking
    setclang:
	@echo "Setting clang"
	$(eval CXX = clang++)
	$(eval CXX_LINK = clang++)

    # Phony target to use g++ for compile and linking
    setgcc:
	@echo "Setting g++"
	$(eval CXX = g++-4.8)
	$(eval CXX_LINK = g++-4.8)

    # $< refers to the first dependency
    # Uses static pattern rule to keep from compiling all
    #   objects every time.
    $(OBJS): %.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(LFLAGS) -c $< -o $@ 

    $(DEPS): %.d: %.cpp
	@echo "Generating "$@
	@set -e; rm -f $@; \
      g++-4.8 -MM $(CPPFLAGS) $< > $@.$$$$; \
      sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
      rm -f $@.$$$$
    #g++ -o LibDemo -std=c++11 -I/home/emmanuj/libs/networkit/include -    L/home/emmanuj/libs/networkit/ LibDemo.cpp -lNetworKit -fopenmp
    # $@ refers to the target
    $(EXEC): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS) $(INCLUDES) $(LFLAGS) $(LDFLAGS)

    include $(DEPS)

**Comment by rcurtin** [comment]
I'm willing to bet that the issue here is that your final link isn't properly linking against mlpack.  Maybe do you need to add `/usr/local/lib/` to `LFLAGS`?  I don't see any issues with `Graph::sparsifyGraph()`.

**Comment by ttuethao** [comment]
I have a similar problem. I built the mlpack.dylib successfully. The test however failed for 4 cases but I ignored. I tried to compile the sample program (http://www.mlpack.org/doxygen.php?doc=sample.html), but it failed at linking state, despite my effort in trying include every path I could think of. Here is the command 

<code>
g++-mp-4.9 lab.cpp -o lab.x -std=c++11 -O3 -I /opt/local/include -I /opt/local/include/eigen3 -I /opt/local/include/armadillo_bits -I /opt/local/include/libxml2 -I /usr/local/include  -L ./ -L /opt/local/lib -L /usr/lib -L /usr/local/lib -lmlpack -larmadillo -lxml2 -lblas -llapack
</code>

It failed with the note (sorry, I do not know how to paste the error in the correct format)

<code>
Undefined symbols for architecture x86_64:
  "mlpack::util::PrefixedOutStream::operator<<(std::basic_ostream<char, std::char_traits<char> >& (*)(std::basic_ostream<char, std::char_traits<char> >&))", referenced from:
      bool mlpack::data::Save<double>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double> const&, bool, bool) in cc0ZLSpa.o
      bool mlpack::data::Load<double>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double>&, bool, bool) in cc0ZLSpa.o
  "mlpack::util::PrefixedOutStream::operator<<(std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)", referenced from:
      bool mlpack::data::Save<double>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double> const&, bool, bool) in cc0ZLSpa.o
      bool mlpack::data::Load<double>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double>&, bool, bool) in cc0ZLSpa.o
  "mlpack::Timer::Stop(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      bool mlpack::data::Save<double>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double> const&, bool, bool) in cc0ZLSpa.o
      bool mlpack::data::Load<double>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double>&, bool, bool) in cc0ZLSpa.o
  "mlpack::Timer::Start(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      bool mlpack::data::Save<double>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double> const&, bool, bool) in cc0ZLSpa.o
      bool mlpack::data::Load<double>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double>&, bool, bool) in cc0ZLSpa.o
  "std::ctype<char>::_M_widen_init() const", referenced from:
      bool arma::diskio::load_raw_ascii<double>(arma::Mat<double>&, std::basic_istream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in cc0ZLSpa.o
      bool arma::diskio::load_csv_ascii<double>(arma::Mat<double>&, std::basic_istream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in cc0ZLSpa.o
      void mlpack::util::PrefixedOutStream::BaseLogic<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in cc0ZLSpa.o
      void mlpack::util::PrefixedOutStream::BaseLogic<unsigned long long>(unsigned long long const&) in cc0ZLSpa.o
  "std::__throw_out_of_range_fmt(char const*, ...)", referenced from:
      void mlpack::util::PrefixedOutStream::BaseLogic<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in cc0ZLSpa.o
      bool mlpack::data::Save<double>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double> const&, bool, bool) in cc0ZLSpa.o
      void mlpack::util::PrefixedOutStream::BaseLogic<unsigned long long>(unsigned long long const&) in cc0ZLSpa.o
      bool mlpack::data::Load<double>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arma::Mat<double>&, bool, bool) in cc0ZLSpa.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
</code>
I'm sure the library is in /usr/local/lib
<code>
$ ls /usr/local/lib/libmlpack.
libmlpack.1.0.dylib  libmlpack.1.dylib    libmlpack.dylib
</code>
I am very grateful if you can see a problem in my stuff... Thanks a lot.

**Comment by ttuethao** [comment]
OK. I found out that this is likely an incompatibility between c++ and g++-mp-4.9, or a bug in g++-mp-4.9. If I changed the compiler to c++, things then  work just fine (I am not used to  use c++). Besides, I could not build mlpack with g++-mp-4.9 with the same linking errors.

**Comment by rcurtin** [comment]
So I don't have a Mac on which to try to reproduce this, but I do have an idea, at least.

emmanuj: is the compiler being used to compile mlpack the same as the compiler being used to compile your k-means program? (i.e. did you compile mlpack with g++-mp-4.8?)

**Comment by rcurtin** [comment]
Oops, did not mean to close this. Stray click.

ttuethao: thanks for the additional information. Do you mean that mlpack ('make mlpack') will not compile with g++-mp-4.9?

**Comment by ttuethao** [comment]
@rcurtin: yes, nothing compiled, g++ (version 5.1), g++-mp-4.8, g++-mp-4.9, [except clang]. I reported here https://github.com/mlpack/mlpack/issues/442

**Comment by rcurtin** [comment]
ttuethao: okay, we can consider that problem in #442 then.

**Comment by rcurtin** [comment]
Closing for inactivity.  (Reopen if necessary.)
