### ISSUE TITLE
mlpack-3.1.1 fails to compile with Ensmallen 2.1.0 release

### ISSUE THREAD

**Issue by jwdinius** [mlpack/mlpack#2008]
#### Issue description

When trying to use build mlpack 3.1.1 with Ensmallen 2.1.0, I receive the following compiler error:

```
/mlpack-3.1.1/src/mlpack/methods/matrix_completion/matrix_completion.cpp: In member function 'void mlpack::matrix_completion::MatrixCompl
etion::Recover(arma::mat&)':
/mlpack-3.1.1/src/mlpack/methods/matrix_completion/matrix_completion.cpp:95:46: error: no matching function for call to 'ens::LRSDPFuncti
on<ens::SDP<arma::SpMat<double> > >::GetInitialPoint()'
   recovered = sdp.Function().GetInitialPoint();
                                              ^
In file included from /usr/local/include/ensmallen_bits/sdp/lrsdp.hpp:18:0,
                 from /usr/local/include/ensmallen.hpp:104,
                 from /mlpack-3.1.1/src/mlpack/methods/matrix_completion/matrix_completion.hpp:16,
                 from /mlpack-3.1.1/src/mlpack/methods/matrix_completion/matrix_completion.cpp:13:
/usr/local/include/ensmallen_bits/sdp/lrsdp_function.hpp:97:18: note: candidate: template<class MatType> const MatType& ens::LRSDPFunctio
n<SDPType>::GetInitialPoint() const [with MatType = MatType; SDPType = ens::SDP<arma::SpMat<double> >]
   const MatType& GetInitialPoint() const
                  ^
/usr/local/include/ensmallen_bits/sdp/lrsdp_function.hpp:97:18: note:   template argument deduction/substitution failed:
/mlpack-3.1.1/src/mlpack/methods/matrix_completion/matrix_completion.cpp:95:46: note:   couldn't deduce template parameter 'MatType'
   recovered = sdp.Function().GetInitialPoint();
                                              ^
[ 29%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/methods/neighbor_search/unmap.cpp.o
src/mlpack/CMakeFiles/mlpack.dir/build.make:927: recipe for target 'src/mlpack/CMakeFiles/mlpack.dir/methods/matrix_completion/matrix_com
pletion.cpp.o' failed
make[2]: *** [src/mlpack/CMakeFiles/mlpack.dir/methods/matrix_completion/matrix_completion.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:301: recipe for target 'src/mlpack/CMakeFiles/mlpack.dir/all' failed
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/bash -c cd mlpack* && mkdir build && cd build     && cmake -DDEBUG=OFF -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUIL
D_TESTS=OFF ..     && make -j2 && make install' returned a non-zero code: 2
```

#### Your environment

 * version of mlpack: 3.1.1
 * operating system: Ubuntu 16.04
 * compiler: gcc 5.4.0
 * version of dependencies (Boost/Armadillo): (1.58.0, 9.700.2)
 * any other environment information you think is relevant:
`Dockerfile`:

```
FROM ubuntu:xenial

# USE BASH
SHELL ["/bin/bash", "-c"]

# INSTALL SYSTEM-WIDE DEPENDENCIES
RUN apt-get update && apt-get install -y --fix-missing cmake pkg-config git wget \
    build-essential libboost-all-dev zip
RUN apt-get install -y --allow-unauthenticated libomp-dev libopenblas-dev liblapack-dev \
    libarpack++2-dev

# INSTALL ARMADILLO
RUN wget http://sourceforge.net/projects/arma/files/armadillo-9.700.2.tar.xz \
    && tar -xf armadillo-9.700.2.tar.xz
RUN cd armadillo* && mkdir build && cd build \
    && cmake .. && make -j2 && make install

# INSTALL ENSMALLEN
#RUN wget http://ensmallen.org/files/ensmallen-1.15.1.tar.gz \
#    && tar -xzf ensmallen-1.15.1.tar.gz
RUN wget https://github.com/mlpack/ensmallen/archive/2.10.0.zip \
    && unzip 2.10.0
RUN cd ensmallen* && mkdir build && cd build \
    && cmake -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS="-Werror" .. \
    && make -j2 && make install

# INSTALL MLPACK
RUN wget https://www.mlpack.org/files/mlpack-3.1.1.tar.gz \
    && tar -xzf mlpack-3.1.1.tar.gz
RUN cd mlpack* && mkdir build && cd build \
    && cmake -DDEBUG=OFF -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_TESTS=OFF .. \
    && make -j2 && make install

# INSTALL NLOHMANN_JSON (downloaded from github)
RUN wget https://github.com/nlohmann/json/archive/release/3.7.0.zip \
    && unzip 3.7.0.zip
RUN cd json* && mkdir build && cd build \
    && cmake .. \
    && make -j2 && make install

# INSTALL OR-TOOLS (from binary)
RUN apt-get install -y zlib1g-dev
RUN wget https://github.com/google/or-tools/releases/download/v7.3/or-tools_ubuntu-16.04_v7.3.7083.tar.gz \
    && tar -xvf or-tools_ubuntu-16.04_v7.3.7083.tar.gz
ENV ORTOOLS_ROOT=/or-tools_Ubuntu-16.04-64bit_v7.3.7083

# REMOVE ARCHIVES
RUN rm *.tar.* && rm *.zip
```

#### Steps to reproduce

`docker build --network=host -t image_name .` from directory with `Dockerfile` above in it.

#### Expected behavior

The image build should complete successfully.

#### Actual behavior

Image failed to build; see original error for info.

**Comment by rcurtin** [comment]
Thanks for the report.  I thought that this could not happen due to our build/test setup but I see that we must have a "hole" somewhere.  I'll look into both of these things and should have a fix for both tonight.

**Comment by rcurtin** [comment]
I did the following:

 * Opened ensmallen#131 to fix a few bugs that happened
 * Opened mlpack#2008 to handle compatibility from the mlpack side
 * Created a job that runs on ensmallen PRs to ensure that it will still compile mlpack master, to ensure this doesn't happen again

Thanks again for the report. :+1:
