### ISSUE TITLE
[MSVC] error C2766: explicit specialization; 'cereal::detail::binding_name<mlpack::Layer<arma::mat>>' has already been defined

### ISSUE THREAD

**Issue by QuellaZhang** [mlpack/mlpack#4166]
Hi All,

We build mlpack using the latest MSVC to detect compiler regressions. After updating the SHA to 744e806, we observed that `error C2766: explicit specialization; 'cereal::detail::binding_name<mlpack::Layer<arma::mat>>' has already been defined`, could you take a look? Thanks you.

**Build steps:**
1. git clone https://github.com/Microsoft/vcpkg C:\gitP\Microsoft\vcpkg
2. cd /d C:\gitP\Microsoft\vcpkg
3. bootstrap-vcpkg.bat
4. vcpkg install --x-buildtrees-root=C:\vcpkgbt --keep-going --recurse armadillo cereal ensmallen --triplet x64-windows --clean-after-build
5. git clone https://github.com/mlpack/mlpack.git C:\gitP\mlpack\mlpack
6. mkdir C:\gitP\mlpack\mlpack\build_amd64
7. cd /d C:\gitP\mlpack\mlpack\build_amd64
8. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.26100.0 -DDEBUG=OFF -DPROFILE=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=C:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows .. 
9. msbuild /m /p:Platform=x64 /p:Configuration=Release /p:PreferredToolArchitecture=x64 mlpack.sln /t:Rebuild

**Build log:** [Build.log](https://github.com/user-attachments/files/27948198/Build.log)

**Error info:**
```
C:\gitP\mlpack\mlpack\src\mlpack\tests\ann\models\yolov3_tests.cpp(21,1): error C2766: explicit specialization; 'cereal::detail::binding_name<mlpack::Layer<arma::mat>>' has already been defined
C:\gitP\mlpack\mlpack\src\mlpack/methods/ann/layer/serialization.hpp(106,1): note: see previous definition of 'cereal::detail::binding_name<mlpack::Layer<arma::mat>>'
C:\gitP\mlpack\mlpack\src\mlpack\tests\ann\models\yolov3_tests.cpp(21,1): error C2766: explicit specialization; 'cereal::detail::init_binding<mlpack::Layer<arma::mat>,cereal::detail::polymorphic_binding_tag>' has already been defined
C:\gitP\mlpack\mlpack\src\mlpack/methods/ann/layer/serialization.hpp(106,1): note: see previous definition of 'cereal::detail::init_binding<mlpack::Layer<arma::mat>,cereal::detail::polymorphic_binding_tag>'
C:\gitP\mlpack\mlpack\src\mlpack\tests\ann\models\yolov3_tests.cpp(22,1): error C2766: explicit specialization; 'cereal::detail::binding_name<mlpack::Identity<arma::mat>>' has already been defined
C:\gitP\mlpack\mlpack\src\mlpack/methods/ann/layer/serialization.hpp(106,1): note: see previous definition of 'cereal::detail::binding_name<mlpack::Identity<arma::mat>>'
C:\gitP\mlpack\mlpack\src\mlpack\tests\ann\models\yolov3_tests.cpp(22,1): error C2766: explicit specialization; 'cereal::detail::init_binding<mlpack::Identity<arma::mat>,cereal::detail::polymorphic_binding_tag>' has already been defined
C:\gitP\mlpack\mlpack\src\mlpack/methods/ann/layer/serialization.hpp(106,1): note: see previous definition of 'cereal::detail::init_binding<mlpack::Identity<arma::mat>,cereal::detail::polymorphic_binding_tag>'
C:\gitP\mlpack\mlpack\src\mlpack\tests\ann\models\yolov3_tests.cpp(23,1): error C2766: explicit specialization; 'cereal::detail::binding_name<mlpack::MultiLayer<arma::mat>>' has already been defined
C:\gitP\mlpack\mlpack\src\mlpack/methods/ann/layer/serialization.hpp(106,1): note: see previous definition of 'cereal::detail::binding_name<mlpack::MultiLayer<arma::mat>>'
C:\gitP\mlpack\mlpack\src\mlpack\tests\ann\models\yolov3_tests.cpp(23,1): error C2766: explicit specialization; 'cereal::detail::init_binding<mlpack::MultiLayer<arma::mat>,cereal::detail::polymorphic_binding_tag>' has already been defined
```

**Comment by conradsnicta** [comment]
@rcurtin Maybe this would be an easy fix before the 4.8.0 release?

**Comment by rcurtin** [comment]
@conradsnicta good point; it was easier to debug than I thought.

@QuellaZhang are you able to test with a patch?  If so, can you try the changes in #4168 to verify they work for your situation?  I think that they will, but I don't compile with MSVC so I can't easily check myself.

**Comment by QuellaZhang** [comment]
@rcurtin, thanks for the quick fix. I verified the patch, it works! MLPACK passed locally.

**Comment by rcurtin** [comment]
Thanks! #4168 is merged and will be a part of the next release.
