### PR TITLE
Download old boost version if the compiler is tooo.. old

### LINKED ISSUE #2939: mlpack no longer compiles on RHEL 7 / CentOS 7
Tried to compile mlpack master (as of 07 May 2021) on a standard RHEL 7 / CentOS 7 box and got this:

```
(...)
-- Could NOT find Boost: Found unsuitable version "1.53.0", but required is at least "1.58" (found /usr/include)
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
(...)
-- Found Boost: /home/blah/git/mlpack-master/build/deps/boost_1_76_0/ (found version "1.76.0")  
(...)
In file included from /home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/config.hpp:61:0,
                 from /home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/variant/detail/config.hpp:16,
                 from /home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/variant/variant_fwd.hpp:16,
                 from /home/blah/git/mlpack-master/build/deps/cereal-1.3.0/include/cereal/types/boost_variant.hpp:41,
                 from /home/blah/git/mlpack-master/src/mlpack/prereqs.hpp:91,
                 from /home/blah/git/mlpack-master/build/src/mlpack/cotire/mlpack_CXX_prefix.cxx:4,
                 from /home/blah/git/mlpack-master/build/src/mlpack/cotire/mlpack_CXX_prefix.hxx:4:
/home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/tools/precision.hpp:41:83: error: redeclaration ‘int boost::math::tools::digits()’ differs in ‘constexpr’
 inline BOOST_MATH_CONSTEXPR int digits(BOOST_MATH_EXPLICIT_TEMPLATE_TYPE_SPEC(T)) BOOST_NOEXCEPT
                                                                                   ^
In file included from /home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/tools/precision.hpp:16:0,
                 from /home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/tools/fraction.hpp:13,
                 from /home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/special_functions/gamma.hpp:19,
                 from /home/blah/git/mlpack-master/src/mlpack/core/kernels/spherical_kernel.hpp:13,
                 from /home/blah/git/mlpack-master/src/mlpack/core.hpp:109,
                 from /home/blah/git/mlpack-master/src/mlpack/bindings/tests/clean_memory.cpp:14:
/home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/policies/policy.hpp:25:15: error: from previous declaration ‘constexpr int boost::math::tools::digits()’
 constexpr int digits(BOOST_MATH_EXPLICIT_TEMPLATE_TYPE(T)) noexcept;
(...)
In file included from /home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/tools/series.hpp:16:0,
                 from /home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/special_functions/gamma.hpp:18,
                 from /home/blah/git/mlpack-master/src/mlpack/core/kernels/spherical_kernel.hpp:13,
                 from /home/blah/git/mlpack-master/src/mlpack/core.hpp:109,
                 from /home/blah/git/mlpack-master/src/mlpack/bindings/cli/print_help.hpp:15,
                 from /home/blah/git/mlpack-master/src/mlpack/bindings/cli/print_help.cpp:13:
/home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/tools/config.hpp:261:77: error: redeclaration ‘T boost::math::tools::epsilon()’ differs in ‘constexpr’
 #  define BOOST_MATH_NOEXCEPT(T) noexcept(boost::is_floating_point<T>::value)
                                                                             ^
/home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/tools/precision.hpp:246:82: note: in expansion of macro ‘BOOST_MATH_NOEXCEPT’
 inline BOOST_MATH_CONSTEXPR T epsilon(BOOST_MATH_EXPLICIT_TEMPLATE_TYPE_SPEC(T)) BOOST_MATH_NOEXCEPT(T)
                                                                                  ^
In file included from /home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/tools/precision.hpp:16:0,
                 from /home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/tools/fraction.hpp:13,
                 from /home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/special_functions/gamma.hpp:19,
                 from /home/blah/git/mlpack-master/src/mlpack/core/kernels/spherical_kernel.hpp:13,
                 from /home/blah/git/mlpack-master/src/mlpack/core.hpp:109,
                 from /home/blah/git/mlpack-master/src/mlpack/bindings/cli/print_help.hpp:15,
                 from /home/blah/git/mlpack-master/src/mlpack/bindings/cli/print_help.cpp:13:
/home/blah/git/mlpack-master/build/deps/boost_1_76_0/boost/math/policies/policy.hpp:27:13: error: from previous declaration ‘constexpr T boost::math::tools::epsilon()’
 constexpr T epsilon(BOOST_MATH_EXPLICIT_TEMPLATE_TYPE(T)) noexcept(std::is_floating_point<T>::value);
(...)
```

RHEL 7 / CentOS 7 has gcc 4.8 as the default compiler.
```
$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
```

### PR DESCRIPTION
**Pull request by shrit**
This pull request fixes #2939

Signed-off-by: Omar Shrit <omar@shrit.me>

### CODE REVIEW

**Comment by shrit** [comment]
@rcurtin, I am happy to host it on mlpack website and change the link in order to avoid lost link issues. Let me know what do you think

**Comment by birm** [comment]
Unfortunately, boost doesn't seem too consistent about its compiler compatibility notes. Looks like 1.62 works with gcc >= 4.5 (https://www.boost.org/doc/libs/1_62_0/libs/log/doc/html/log/installation.html)

I'll take some time to test on a centos 7 vm.

**Comment by rcurtin** [comment]
> @rcurtin, I am happy to host it on mlpack website and change the link in order to avoid lost link issues. Let me know what do you think

If it works reasonably well as-is, I'm fine sticking with the external link.  After all, we are hoping to remove it soon anyway. :)

**Review by rcurtin — APPROVED** [review]
At the very least, even if there are other issues with older compilers in #2939, this should work. :+1:

**Comment by shrit** [comment]
@rcurtin Yeah, totally agreed, in the meanwhile, I hope at least their website links keep working.

**Review by birm — APPROVED** [review]
I'm not sure what environment this now fixes, but it worka as described
