### ISSUE TITLE
/usr/lib/libarmadillo.so.4: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by armanschwarz** [mlpack/mlpack#494]
I am trying to build a simple program that uses mlpack. As a test case, I've copied the *perceptron_test.cpp* from mlpack trunk into a source folder and am now attempting to link against mlpack to get it to run.

I'm using mlpack from trunk (3b926fd86ab143eb8af7327b9fb89fead7538df0) and armadillo from ubuntu 14.04 (http://packages.ubuntu.com/trusty/libarmadillo-dev). I am running boost 1.55.

I have the following directory structure in my source tree:
```
/
  CMakeLists.txt
  cmake/
    FindLibXml2.cmake
    Findmlpack.cmake
  test/
  CMakeLists.txt
  main.cpp
  perceptron_test.cpp
```
The contents of the parent CMakeLists.txt file is:

```
cmake_minimum_required(VERSION 3.0)                                                 
                                                                                    
add_definitions(-std=c++14 -Wpedantic -Wall -Werror)                                
add_definitions(-DBOOST_LOG_DYN_LINK)                                               
                                                                                    
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake" ${CMAKE_MODULE_PATH})             
                                                                                    
find_package(Boost 1.55.0)                                                          
find_package(mlpack)                                                                
find_package(LibXml2)                                                               
                                                                                    
enable_testing()                                                                    
                                                                                    
include_directories(                                                                
    ${PROJECT_SOURCE_DIR}                                                           
    ${LIBXML2_INCLUDE_DIRS}                                                         
    )                                                                               
                                                                                    
add_subdirectory(test)                                                              
```

The context of the CMakeLists.txt file in /test is:
```
cmake_minimum_required(VERSION 3.0)                                                 
                                                                                    
add_executable(masterTest                                                           
    main.cpp                                                                        
    perceptron_test.cpp                                                             
    )                                                                               
                                                                                    
target_link_libraries(masterTest                                                    
    mlpack                                                                          
    ${BOOST_unit_test_framework_LIBRARY}                                            
)                                                                                   
                                                                                    
add_test(masterTest masterTest)                                                     
```

when I build with g++ version 5.1.0 I get the following:
```
usr@usr-desktop:~/Documents/neuro.build$ ninja
[1/1] Linking CXX executable test/masterTest
FAILED: : && /usr/bin/g++      test/CMakeFiles/masterTest.dir/main.cpp.o test/CMakeFiles/masterTest.dir/perceptron_test.cpp.o  -o test/masterTest  -rdynamic -lmlpack && :
/usr/bin/ld: test/CMakeFiles/masterTest.dir/perceptron_test.cpp.o: undefined reference to symbol 'wrapper_dgemm_'
//usr/lib/libarmadillo.so.4: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

Interestingly, when I build the tests (including the *perceptron_test.cpp*) that ships with mlpack directly, these tests link fine.

I don't have any other versions of armadillo installed on my machine.

**Comment by rcurtin** [comment]
Hi there,

You need to link against Armadillo in your call to `target_link_libraries()`.  Take a look at the CMakeLists.txt in the mlpack repository for more information on how to find Armadillo.  Or, you can just add "armadillo" to the `target_link_libraries()` line and hope that libarmadillo.so is on the linker's default search path. :)

Feel free to reopen if that wasn't the issue, but I'm pretty confident it is in this case.
